### ISSUE TITLE
how to write TARGETPLATFORM in istio-proxyv2 dockerfile?

### ISSUE THREAD

**Issue by DrowringMan** [raspbernetes/multi-arch-images#137]
i will build istio images on arm platform, how should i write this parameter in dockerfile

**Comment by xUnholy** [comment]
This has already been completed here https://github.com/raspbernetes/multi-arch-images/blob/master/build/istio-proxyv2/Dockerfile

Is there something you see missing? Unless this is for the envoy image?

**Comment by DrowringMan** [comment]
this  parameter  in dockerfile  6 row，i dont know  write linux/arm64 or arm64 , maybe GOARM=64 GOARCH=arm GOOS=linux?

**Comment by DrowringMan** [comment]
this dockerfile 6 rows parameter, i write linux/arm64, but  dockerfile 17 rows will not get ， i will go write GOARM=7 in dockerfile 17 row，is ok？

**Comment by RobReus** [comment]
When you use `linux/arm64`, the variable `GOARM` will be empty as it should be. That variable should only be set for 32 bit ARM versions and **not** for arm64 (64 bit). Perhaps you can share any possible error messages you are getting when you use the Dockerfile as is with `linux/arm64` set as target platform?

Do note: when building this docker image, you should do this on an arm64 systtem or you **need** to use buildx in order to build docker images for other platforms (cross-build). See https://docs.docker.com/buildx/working-with-buildx/ and https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408 for more info.

**Comment by xUnholy** [comment]
@DrowringMan unfortunately envoy isn't going to be possible to build for armv7 as much as we've invested time to do so it's not possible at this current time.

**Comment by DrowringMan** [comment]
problem is resolv, build success,thank you for your help @RobReus @xUnholy
