### ISSUE TITLE
support prometheus-operator

### ISSUE THREAD

**Issue by HaveFun83** [raspbernetes/multi-arch-images#61]
Hi 
is it possible to support multi-arch builds for the prometheus-operator?
https://github.com/coreos/prometheus-operator

If yes i could working on an MR.
regards

**Comment by onedr0p** [comment]
@HaveFun83 I'd start out by listing all the images that it uses, like grafana, node-exporter etc...

**Comment by xUnholy** [comment]
@HaveFun83 we'd absolutely be open to supporting any and all images for ARM.

**Comment by damm** [comment]
I ended up building an [image](https://hub.docker.com/repository/docker/damm/kube-state-metrics) for `-kube-state-metrics` as the current release is not arm64.

**Comment by xUnholy** [comment]
@HaveFun83 did you make any lead way with investigating and getting prometheus-operator support for ARM into the repository? I would love to hear how you went as I'm also looking at using it myself currently.

**Comment by HaveFun83** [comment]
@xUnholy sorry been a bit busy the last weeks. Will try to create a PR for it later this week.

**Comment by mcristina422** [comment]
This is being worked on upstream

https://github.com/coreos/prometheus-operator/pull/3177

**Comment by paulfantom** [comment]
> which other applications around the stack also missing multi-arch support

Just a note: currently, there are missing ARMv7 and ARM64 images for:
- prometheus-operator (currently worked on)
- [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)
- [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy)

Everything else already supports ARMv7 and ARM64.

**Comment by xUnholy** [comment]
@mcristina422 @paulfantom Thanks for bringing that to my attention regarding prometheus-operator being worked on which is fantastic news! 

We also identified some other dependencies that need to be compiled, would you be able to confirm if these are in scope for your changes @paulfantom otherwise we'll continue to update these ones, and then once your PR is merged we can use your official upstream changes for the
prometheus-operator.

**Comment by xUnholy** [comment]
Can confirm this also need to be supported from what I'm seeing in my latest test `jettech/kube-webhook-certgen:v1.0.0`

**Comment by xUnholy** [comment]
I've managed to use the `prometheus-operator` helm chart and deploy almost the full stack with all the corresponding required images in multi-architecture for ARM(64) suppose

https://github.com/raspbernetes/k8s-gitops/blob/develop/namespaces/monitoring/prometheus-operator/prometheus-operator.yaml

Special thanks to @stefancrain for pushing the last few images out.

@paulfantom I didn't come across  `kube-rbac-proxy` when using the chart, would you be able to share more about when it is used?

**Comment by paulfantom** [comment]
I am not using the helm chart, but [coreos/kube-prometheus](https://github.com/coreos/kube-prometheus) project.

As for prometheus-opeator, since yesterday we are pushing images for amd64, armv7, and arm64 built from `master` branch. You can see them here: https://quay.io/repository/coreos/prometheus-operator?tag=latest&tab=tags

As for kube-state-metrics and kube-rbac-proxy - PRs are open and in review :)

**Comment by xUnholy** [comment]
Good to see the wider support and adoption of images for multi-architecture images. Once the images are in an official release version we'll deprecate our version and promote the upstream - thanks for your good work 👍

**Comment by xUnholy** [comment]
@stefancrain we might need to add `kube-rbac-proxy` support and I think we can wrap this issue up.

**Comment by xUnholy** [comment]
This is being closed for an example of all the helm values in a helm release manifest please look here: https://github.com/raspbernetes/k8s-gitops/blob/develop/namespaces/monitoring/prometheus-operator/prometheus-operator.yaml
